### ISSUE TITLE
Topic tests failing

### ISSUE THREAD

**Issue by Haarolean** [provectus/kafka-ui#1016]
```
[ERROR] com.provectus.kafka.ui.topics.TopicTests  Time elapsed: 0.483 s  <<< ERROR!
java.lang.NoSuchMethodError: 'java.lang.String io.netty.util.internal.ObjectUtil.checkNonEmptyAfterTrim(java.lang.String, java.lang.String)'
	at com.provectus.kafka.ui.topics.TopicTests.beforeAll(TopicTests.java:27)
```

**Comment by Haarolean** [comment]
Broken since #931
